- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/list-namespaces.adoc
`change`, `decision`, `requirement/quality`, `requirement/functional`, `dependency`
> Add how to list namespaces

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/explanation/differences-to-public.adoc
`change`, `decision`, `requirement/quality`, `requirement/functional`, `dependency`
> Document differences to APPUiO Public

- docs/modules/ROOT/pages/explanation/differences-to-public.adoc
`change`, `decision`, `requirement/quality`, `requirement/functional`, `dependency`
> Exclude backups from offering

- docs/modules/ROOT/pages/references/default-quota.adoc
> Rewrite `Default Quota` reference documentation

- docs/modules/ROOT/pages/references/default-quota.adoc
> Document quota for activeDeadlineSeconds

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/explanation/unit-prefixes.adoc
> Describe Unit Prefixes

- docs/modules/ROOT/pages/explanation/organizations-and-rbac.adoc
> Add documentation on transferring projects

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/use-integrated-registry.adoc
> Add how-to for using integrated registry

- docs/modules/ROOT/pages/references/zones.adoc
> Add registry domains to zones reference

- Makefile
- README.adoc
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/tutorials/migration.adoc
This PR provides a solution for issue #39.
> Migration Tutorial: From Public to Cloud

- docs/modules/ROOT/pages/tutorials/migration.adoc
> Migration Tutorial: Removed API versions

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/explanation/client-throttling.adoc
> Describe Client Throttling behaviour

- docs/modules/ROOT/pages/references/zones.adoc
> Add lpg 2 production zone and remove lpg 0 and lpg 1 Test zones

- docs/modules/ROOT/pages/how-to/getting-a-certificate.adoc
> Give information about the TLS secret for Ingress

- docs/modules/ROOT/pages/how-to/getting-a-certificate.adoc
> Clarify Ingress object example for TLS certificates

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/explanation/storage-classes.adoc
- docs/modules/ROOT/pages/how-to/encrypted-volumes.adoc
> Add how-to page to setup encrypted volumes on cloudscale

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/manage-projects-and-namespaces.adoc
> How to explaining management of projects and namespaces

- docs/modules/ROOT/pages/how-to/manage-projects-and-namespaces.adoc
Documents change in https://github.com/appuio/component-appuio-cloud/pull/55 
> Add tip that creating namespaces using a SA is possible

- Makefile
Updates the `make preview` command to the latest version.
> Updated antora-preview version

- docs/modules/ROOT/pages/tutorials/migration.adoc
> Fix typo in Migration Tutorial

- docs/modules/ROOT/pages/explanation/unit-prefixes.adoc
> Update binary prefix typo

- docs/modules/ROOT/pages/explanation/organizations-and-rbac.adoc
> Fix typo in note about moving project between organizations

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/install-postgres-db-helm.adoc
This how-to guide is the docs result of the question/discussion here: https://github.com/appuio/appuio-cloud-community/discussions/27
> Add how-to guide for PostgreSQL installation via Helm

- docs/modules/ROOT/pages/search.adoc
> Enabling OpenSearch support

- docs/modules/ROOT/pages/explanation/storage-classes.adoc
> Add a note about size restrictions for cloudscale.ch bulk volumes

- docs/modules/ROOT/pages/references/default-quota.adoc
> Fix broken link

- docs/modules/ROOT/pages/tutorials/migration.adoc
* Proposal to create ALIAS or A records if CNAME isn't an option.
> Add alternatives if CNAME isn't an option

- docs/modules/ROOT/pages/how-to/grant-access.adoc
> Page about granting access to projects and namespaces

- docs/modules/ROOT/pages/explanation/storage-classes.adoc
> Add clarification regarding volume-level encryption on Rook

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/check-cpu-requests.adoc
> Add how-to for investigating and addressing memory-per-core ratio violations

- docs/modules/ROOT/pages/how-to/check-cpu-requests.adoc
> Mention usage dashboard available in the web console

- docs/modules/ROOT/pages/explanation/differences-to-public.adoc
> Mention change in log retention time

- docs/modules/ROOT/pages/tutorials/getting-started/crystal-terminal.adoc
- docs/modules/ROOT/pages/tutorials/getting-started/perl-terminal.adoc
Updated code snippets for the Crystal and Perl examples.
> Updated code snippets

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/create-bucket.adoc
Add an example on how to provision a bucket.
> Add simple how-to for buckets

- Makefile
- docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
Fixes wrong rendering of the `menu:` Asciidoctor macro.
> Wrong use of the menu macro

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/use-vpa.adoc
> Added page to show how to use Vertical Pod Autoscaler recommendations

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/monitor-pvc-usage.adoc
> How-To: Monitor PVC Usage

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/explanation/pod-security-admissions.adoc
> Added page about Pod Security Admissions

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/explanation/fair-use-policy.adoc
> Add fair use policy explanation page

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/choose-node-class.adoc
- docs/modules/ROOT/pages/references/node-classes.adoc
Documents how to choose node class if rolled out in [APPU-3949](https://ticket.vshn.net/browse/APPU-3949).
> How-to: Choose Node Class

- docs/modules/ROOT/pages/references/node-classes.adoc
> Fix chapter node classes subtitle

- docs/modules/ROOT/pages/how-to/encrypted-volumes.adoc
Adds the configured cipher to the page "Setup Encrypted Volumes"
> Add cipher to encrypted volume how-to

- docs/modules/ROOT/pages/how-to/use-custom-grafana.adoc
> Fix Authorization header on Use Custom Grafana how-to

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/fine-grained-access-examples.adoc
- docs/modules/ROOT/pages/how-to/grant-access.adoc
> Add examples for access control with organizations/teams

- docs/modules/ROOT/pages/explanation/organizations-and-rbac.adoc
> Add user workload monitoring role bindings in "Organizations and RBAC" explanation

- docs/modules/ROOT/pages/how-to/fine-grained-access-examples.adoc
- docs/modules/ROOT/pages/how-to/grant-access.adoc
> Update how-tos which cover granting access with user workload monitoring RBAC

- docs/modules/ROOT/pages/tutorials/getting-started.adoc
> Warn about zone setup delay with default organization

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/monitor-http-endpoints.adoc
- docs/modules/ROOT/pages/how-to/use-custom-grafana.adoc
- docs/modules/ROOT/pages/tutorials/demo-app/ghost.adoc
- docs/modules/ROOT/pages/tutorials/demo-app/gitea.adoc
- docs/modules/ROOT/pages/tutorials/demo-app/index.adoc
- docs/modules/ROOT/pages/tutorials/demo-app/mastodon.adoc
- docs/modules/ROOT/pages/tutorials/demo-app/odoo.adoc
- docs/modules/ROOT/pages/tutorials/demo-app/takahe.adoc
- docs/modules/ROOT/pages/tutorials/demo-app/wordpress.adoc
The VSHN Application Catalog lives on its own now.
> Make VSHN Application Catalog documentation external

- docs/modules/ROOT/pages/how-to/use-integrated-registry.adoc
Just like in https://docs.appuio.cloud/user/how-to/connect-gitlab.html
> Create a secret for the registry access sa token

- Makefile
- docs/modules/ROOT/pages/tutorials/getting-started.adoc
This PR updates the instructions in the "Getting Started" guide following the new self-signup feature.
> Updated getting started instructions

- docs/modules/ROOT/pages/how-to/install-postgres-db-helm.adoc
> Add link to AppCat in postgresql tutorial

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/fine-grained-access-examples.adoc
- docs/modules/ROOT/pages/how-to/lower-resource-quotas.adoc
Relates to https://github.com/appuio/component-appuio-cloud/pull/181
> Document how users are able to lower resource quotas

- docs/modules/ROOT/pages/explanation/storage-classes.adoc
> Add mention and link for object storage

- docs/modules/ROOT/pages/how-to/remove-default-networkpolicies.adoc
> Make mention of the new CiliumNetworkPolicy in the appropriate documentation

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/how-to/setup-image-pull-secret.adoc
> Add how-to for setting up an image pull secret
